# Generated by Django 5.0.6 on 2024-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('Medical Doctor', 'Medical Doctor'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Software Developer', 'Software Developer'), ('Architect', 'Architect'), ('Chef', 'Chef'), ('Accountant', 'Accountant'), ('Dentist', 'Dentist'), ('Pharmacist', 'Pharmacist'), ('Psychologist', 'Psychologist'), ('Graphic Designer', 'Graphic Designer'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Artist', 'Artist'), ('Writer', 'Writer'), ('Photographer', 'Photographer'), ('Musician', 'Musician'), ('Dancer', 'Dancer'), ('Marketing Specialist', 'Marketing Specialist'), ('Consultant', 'Consultant'), ('Financial Advisor', 'Financial Advisor'), ('Real Estate Agent', 'Real Estate Agent'), ('IT Specialist', 'IT Specialist'), ('Web Developer', 'Web Developer'), ('Data Scientist', 'Data Scientist'), ('Project Manager', 'Project Manager'), ('Human Resources Manager', 'Human Resources Manager'), ('Event Planner', 'Event Planner'), ('Fitness Trainer', 'Fitness Trainer'), ('Interior Designer', 'Interior Designer'), ('Journalist', 'Journalist'), ('Translator', 'Translator'), ('Law Enforcement Officer', 'Law Enforcement Officer'), ('Firefighter', 'Firefighter'), ('Paramedic', 'Paramedic'), ('Flight Attendant', 'Flight Attendant'), ('Pilot', 'Pilot'), ('Veterinarian', 'Veterinarian'), ('Biologist', 'Biologist'), ('Chemist', 'Chemist'), ('Geologist', 'Geologist'), ('Meteorologist', 'Meteorologist'), ('Librarian', 'Librarian'), ('Social Worker', 'Social Worker'), ('others', 'others')], max_length=50),
        ),
    ]
