# Generated by Django 5.0.6 on 2024-05-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_meeting_is_done_alter_user_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='is_done',
            new_name='is_messting_done',
        ),
    ]
