# Generated by Django 5.0.6 on 2024-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_is_messting_done_meeting_is_meeting_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_meetings', models.IntegerField(default=10)),
            ],
        ),
    ]
